options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/sound-velocity-370109/locations/northamerica-northeast2/workerPools/jora-dev-build-pool'

substitutions:
  _JORA_DEV_PROJECT_ID: sound-velocity-370109
  _SVC_NAME: holiday-svc
  _SVC_ZONE: northamerica-northeast2

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: build-service
    args: [ 'build', '-t', 'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: tag-service
    args: [ 'tag',
            'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME:latest',
            'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME:$SHORT_SHA' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: push-service
    args: [ 'push', 'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME:latest' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SVC_NAME-dev'
      - '--image'
      - 'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME:latest'
      - '--region'
      - '$_SVC_ZONE'
      - '--service-account=$_SVC_NAME@$_JORA_DEV_PROJECT_ID.iam.gserviceaccount.com'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'services', 'update', '$_SVC_NAME-dev', '--region', '$_SVC_ZONE' ]
images: [ 'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME:latest',
          'northamerica-northeast2-docker.pkg.dev/$_JORA_DEV_PROJECT_ID/jora-backend/$_SVC_NAME:$SHORT_SHA' ]
